# Generated by Django 4.2.3 on 2024-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_category_news_categories_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="categories",
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
        migrations.AddField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                related_name="news", to="news.category"
            ),
        ),
    ]
