# Generated by Django 4.2.3 on 2024-04-23 15:31

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_remove_news_categories_alter_news_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200, validators=[news.validators.Validate.two_words]
            ),
        ),
    ]
