# Generated by Django 4.2.3 on 2024-04-23 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_created_at_alter_news_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "news list"},
        ),
    ]
